### ISSUE TITLE
Triple Quoted String Fails if there's an extra quote at the end...

### ISSUE THREAD

**Issue by codeviking** [atom-community/language-scala#32]
I submitted an earlier issue related to this (which I can't find now for some reason).  Anyway, syntax highlighting doesn't work for triple quoted strings if the string ends with a quote.  For instance:

![image](https://cloud.githubusercontent.com/assets/801451/8366205/cf0d1722-1b47-11e5-905e-be68d1591307.png)

**Comment by laughedelic** [comment]
I think this is fixed in #33 as well

**Comment by mcous** [comment]
Yup! Released as v1.1.4

**Comment by gangstead** [comment]
Thanks @laughedelic for helping us keep the issues list tidy.
