### ISSUE TITLE
single quote render error

### ISSUE THREAD

**Issue by gaydenko** [atom-community/language-scala#39]
Hi! Probably it is related to https://github.com/atom-community/language-scala/issues/36 fix - unfortunately can not say as far as didn't see the error shown on the attached image before package update.
![atom-scala-apos 2](https://cloud.githubusercontent.com/assets/3740016/12563050/4c036bf4-c3b9-11e5-9f6d-00d9757e0ae2.png)

**Comment by mcous** [comment]
Oh, oops, I know what the problem is. Will be fixed shortly.

**Comment by mcous** [comment]
The breaking changes were reverted and published as v1.1.6. Thanks for catching this!

**Comment by gaydenko** [comment]
Got it, thanks!
