### ISSUE TITLE
Do not support Scala extension .scalaX and .sc 

### ISSUE THREAD

**Issue by edwardwbli** [atom-community/language-scala#48]
Not sure why, but this package can not identify scala source code with extension .scalaX and .sc?

May I have your help to advise?

**Comment by wbazant** [comment]
Hi Edward, I have solved this for you:
https://github.com/atom-community/language-scala/pull/51

Let me know if you require further help to advise.

**Comment by gangstead** [comment]
published `language-scala@v1.1.8`
