### ISSUE TITLE
Syntax highlighting broken for type aliases starting with =

### ISSUE THREAD

**Issue by Jasper-M** [atom-community/language-scala#53]
Type alias definitions starting with `=` are not highlighted correctly.

![screenshot from 2017-01-24 15 59 06](https://cloud.githubusercontent.com/assets/3708353/22252338/1d9409b8-e24e-11e6-884a-71ef730eebc4.png)

language-scala 1.1.8
atom 1.13.0

**Comment by laughedelic** [comment]
Probably resolved in #42?

**Comment by laughedelic** [comment]
I this it is resolved by #42. Here's a screenshot made with v1.1.9:

<img width="186" alt="screen shot 2017-08-11 at 14 37 28" src="https://user-images.githubusercontent.com/766656/29213239-b531b1a8-7ea2-11e7-8cff-35719aaedec2.png">

(I don't know why the name is not yellow like on your screenshot, I guess it's just about the syntax theme; mine is Base16 OceanicNext Dark)

**Comment by Jasper-M** [comment]
Can't check myself, but it looks like it's probably fixed, yes.

**Comment by Jasper-M** [comment]
I can confirm it's fixed.
